steps:
  - name: 'gradle:5.6.2-jdk11'
    entrypoint: 'bash'
    args: [ '-c','gradle','test','sonarqube','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.login=$$SONAR_TOKEN','-Dsonar.organization=sqgate' ]
    secretEnv: ['SONAR_TOKEN']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy' ]

timeout: '1600s'

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/1'
      env: 'SONAR_TOKEN'