steps:
  - name: 'gradle:5.6.2-jdk11'
    entrypoint: 'gradle'
    args: ['test','sonarqube','-Dsonar.projectKey=sonar-gcp-some-pipeline','-Dsonar.host.url=http://localhost:9000 ','-Dsonar.login=06a59fffed6f2508555237a2cde139bed24c4434']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'