steps:
  - name: 'gradle:5.6.2-jdk11'
    entrypoint: 'gradle'
    args: ['test']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'